# System Log and Resource Usage Pattern Analysis
## Notebook 02: Data Preprocessing

This notebook prepares system log and resource usage data for unsupervised learning.
It includes feature selection, data cleaning considerations, and feature scaling
to ensure compatibility with PCA and K-Means clustering.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
os.chdir('/content/drive/MyDrive/system-log-unsupervised-ml')
os.getcwd()

'/content/drive/MyDrive/system-log-unsupervised-ml'

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv("data/raw/system_metrics.csv")
df.head()

,timestamp,cpu_usage,memory_usage,disk_io,network_io,system_load
0,2025-01-01 00:00:00,52.450712,53.248217,85.460256,210.873491,1.480185
1,2025-01-01 00:01:00,42.926035,58.554813,118.751860,249.525533,1.197810
2,2025-01-01 00:02:00,54.715328,52.075801,120.720675,224.635185,1.396575
3,2025-01-01 00:03:00,67.845448,56.920385,138.905214,256.160335,1.928839
4,2025-01-01 00:04:00,41.487699,41.063853,65.325665,282.867975,2.266714

### Preprocessing Strategy

The dataset consists of time-based system metrics such as CPU usage, memory consumption,
disk I/O, network activity, and system load. Since the data is synthetically generated,
it does not contain missing values or inconsistencies.

For unsupervised learning, only numerical features representing system behaviour are required.
The timestamp column is excluded as it does not contribute to clustering or dimensionality reduction.

Feature scaling is essential because PCA and K-Means are distance-based techniques,
and unscaled data can lead to biased results.

In [ ]:
features = df.drop(columns=["timestamp"])
features.head()

   cpu_usage  memory_usage     disk_io  network_io  system_load
0  52.450712     53.248217   85.460256  210.873491     1.480185
1  42.926035     58.554813  118.751860  249.525533     1.197810
2  54.715328     52.075801  120.720675  224.635185     1.396575
3  67.845448     56.920385  138.905214  256.160335     1.928839
4  41.487699     41.063853   65.325665  282.867975     2.266714

In [ ]:
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

# System Log and Resource Usage Pattern Analysis using Unsupervised Machine Learning
## Notebook 02: Data Preprocessing

This notebook details the crucial preprocessing steps required for analyzing system logs and resource usage patterns using unsupervised machine learning. Effective preprocessing ensures data quality, reduces noise, and transforms raw data into a suitable format for algorithms like PCA and K-Means clustering, thereby enhancing the accuracy and interpretability of the subsequent analysis.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
os.chdir('/content/drive/MyDrive/system-log-unsupervised-ml')
print(os.getcwd())

/content/drive/MyDrive/system-log-unsupervised-ml

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv("data/raw/system_metrics.csv")
df.head()

,timestamp,cpu_usage,memory_usage,disk_io,network_io,system_load
0,2025-01-01 00:00:00,52.450712,53.248217,85.460256,210.873491,1.480185
1,2025-01-01 00:01:00,42.926035,58.554813,118.751860,249.525533,1.197810
2,2025-01-01 00:02:00,54.715328,52.075801,120.720675,224.635185,1.396575
3,2025-01-01 00:03:00,67.845448,56.920385,138.905214,256.160335,1.928839
4,2025-01-01 00:04:00,41.487699,41.063853,65.325665,282.867975,2.266714

### Preprocessing Strategy

This section outlines the strategic approach to preprocessing the system metrics dataset for unsupervised learning. The dataset comprises various time-series system performance indicators, including CPU utilization, memory consumption, disk I/O operations, network activity, and overall system load. Given that the dataset is synthetically generated, it inherently exhibits an absence of missing values or data inconsistencies, simplifying the initial data cleaning phase.

For the purpose of unsupervised clustering and dimensionality reduction, only numerical features directly representative of system behavior are retained. The 'timestamp' column is explicitly excluded from the feature set, as its temporal nature does not contribute directly to the pattern identification objectives of clustering or principal component analysis.

Furthermore, feature scaling is an indispensable step prior to applying distance-based algorithms such as PCA and K-Means. Unscaled features, particularly those with disparate magnitudes or units, can lead to biased results, where features with larger numerical ranges disproportionately influence the distance calculations. Therefore, standardization will be applied to ensure all features contribute equally to the analytical process.

In [ ]:
features = df.drop(columns=["timestamp"])
features.head()

   cpu_usage  memory_usage     disk_io  network_io  system_load
0  52.450712     53.248217   85.460256  210.873491     1.480185
1  42.926035     58.554813  118.751860  249.525533     1.197810
2  54.715328     52.075801  120.720675  224.635185     1.396575
3  67.845448     56.920385  138.905214  256.160335     1.928839
4  41.487699     41.063853   65.325665  282.867975     2.266714

In [ ]:
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)
scaled_df = pd.DataFrame(scaled_features, columns=features.columns)
scaled_df.head()

   cpu_usage  memory_usage   disk_io  network_io  system_load
0   0.457327     -0.665341 -0.816584   -1.073997    -0.039544
1  -0.185701     -0.137375  0.016643   -0.606354    -0.519573
2   0.610215     -0.781987  0.065919   -0.907497    -0.181678
3   1.496653     -0.299988  0.521045   -0.526081     0.723154
4  -0.282805     -1.877591 -1.320516   -0.202951     1.297530

In [ ]:
output_dir = "data/processed"
os.makedirs(output_dir, exist_ok=True)
scaled_df.to_csv(os.path.join(output_dir, "system_metrics_scaled.csv"), index=False)
print(f"Processed data saved to: {os.path.join(output_dir, 'system_metrics_scaled.csv')}")

Processed data saved to: data/processed/system_metrics_scaled.csv

### Key Preprocessing Observations

*   **Timestamp Column Removed:** The 'timestamp' column, being non-contributory to clustering, has been successfully excluded from the feature set.
*   **Numerical Data Retention:** The dataset now exclusively contains numerical features, which are appropriate for the chosen unsupervised learning algorithms.
*   **Feature Scaling Applied:** All features have undergone standardization using `StandardScaler`, ensuring uniform contribution to distance-based models.
*   **Dataset Prepared for Analysis:** The preprocessed dataset is now in a clean, scaled format, making it suitable for subsequent dimensionality reduction (e.g., PCA) and clustering (e.g., K-Means) tasks.
*   **Data Persistence:** The scaled dataset has been saved, ensuring reproducibility and availability for subsequent analytical notebooks.